# Generated by Django 3.0.4 on 2020-07-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='User_name',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
