# Generated by Django 3.0.4 on 2020-07-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0005_auto_20200721_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='Excel_file',
            field=models.FileField(upload_to='media'),
        ),
    ]
