# Generated by Django 3.0.4 on 2020-07-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0006_auto_20200721_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='ChromePath',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='document',
            name='ColumnName',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='document',
            name='ImagePath',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
