# Generated by Django 3.0.4 on 2020-07-22 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0009_document_no_of_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='ChromePath',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='document',
            name='ColumnName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='document',
            name='ImagePath',
            field=models.CharField(default='', max_length=100),
        ),
    ]
